spring.application.name=domainseller
server.port=8080
spring.data.mongodb.uri=mongodb://mongo:27017/domainseller
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.mvc.hiddenmethod.filter.enabled=true
